import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'primeflex/primeflex.css';  // Estilos do PrimeFlex
import 'primereact/resources/themes/saga-blue/theme.css';  // Tema do PrimeReact
import 'primereact/resources/primereact.min.css';  // Estilos principais do PrimeReact
import 'primeicons/primeicons.css';  // Ícones do PrimeReact
import "./globals.css";  // Seu arquivo global de estilos

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
